### ISSUE TITLE
An error occured while executing the database patch v10.

### ISSUE THREAD

**Issue by Otoris** [Crimsonfoxy/Statistician-v2#3]
`[Statistician] Critical Error, could not connect to mySQL. Is the database Available? Check config file and try again. (An error occured while executing the database patch v10.)`

This is the exact same config from the previous 1.2.5 version, and I double checked that the DB still exists and reset the password to be safe. I also noticed it gave a different error from the default config info not being true, so the login and stuff is correct and functioning.

Does this perhaps mean I have to wipe my stats? :(

**Comment by Otoris** [comment]
Thanks for updating this btw!

**Comment by Coryf88** [comment]
No, you shouldn't have to ever wipe your current stats unless you choose to. It looks like I made a small mistake in the SQL for v10 that my test MySQL server was fine with. I'll be releasing a new version with the fix shortly.
